
POST http://localhost:4000/products
Content-Type: application/json

{
    "name": "fork",
    "price": "200"
}


#######
GET  http://localhost:4000/products

#######
GET  http://localhost:4000/products/spoon

#######
GET  http://localhost:4000/products/page/4